# name of the workflow. Link to the documentation - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#name
name: CI_Build
# running on push to main and develop branches or on pull reuqests or on manual trigger
on: 
  # manual trigger
  workflow_dispatch:
  push:
    branches:
      - build_with_gh_packages_test
    paths-ignore:
      - '**/README.md'
      - '.devcontainer/**'
  # running on pull requests to main and develop branches
  # pull_request:
  #   branches:
  #     - main
  #     - develop
  #   paths-ignore:
  #     - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # defining permissions for the build job. Link to the documentation - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
      actions: read
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # cache maven packages step - caching maven packages to speed up the build process. Link to the documentation - https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      
      - name: Set up our custom Artifactory instance
        uses: actions/setup-java@v1.4.4
        with: # running setup-java again overwrites the settings.xml
          java-version: 1.8
          # server-id: github # value of repository/id field of the pom.xml
          # server-username: GITHUB_USERNAME_REF  # env variable name for username of GitHub server; value can be anything as it is a transient user
          # server-password: GITHUB_TOKEN_REF # env variable name for GitHub access token
          # # after running this action, the <username> tag contains ${env.GITHUB_USERNAME_REF} and <password> contains ${env.GITHUB_TOKEN_REF}
          settings-path: ${{ github.workspace }}/ci_settings.xml # path to the settings.xml file. Link to the documentation - https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
          overwrite: true # overwrite the settings.xml file if it already exists

      - name: Cache Maven packages
        uses: actions/cache@v3 # defining cache key and restore keys for the cache step. Link to the documentation - https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
        with:
          path: /root/.m2 # path to the directory where maven packages are stored - /root/.m2 in the container
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-build-
      
      - name: Build with Maven
        run: mvn -B package
        env:
          # assign the environment variable env.GITHUB_USERNAME_REF with the previously configured GITHUB_USERNAME
          GITHUB_USERNAME_REF: ${{ secrets.ACTIONS_USER }}
          # assign the environment variable env.GITHUB_TOKEN_REF with the previously configured GITHUB_TOKEN
          GITHUB_TOKEN_REF: ${{ secrets.ACTIONS_TOKEN }}